[package]
name = "jmdict-couch"
version = "0.1.0"
authors = ["Brian Birtles <birtles@gmail.com>"]

[dependencies]
failure = "0.1.1"
memchr = "2.0.1"
quick-xml = "0.11.0"
smallvec = "0.6.0"
structopt = "0.2.2"
